---
title: "Fungi iSeq data analysis"
output: html_notebook
---

```{r}
library(dplyr)
library(tidyr)
library(here)
library(readr)
library(ggplot2)
library(googlesheets4)
library(vegan)
library(readxl)
```

#Analysis
```{r}
gURL <- "https://docs.google.com/spreadsheets/d/1GKWzD0q683oH3I_i5ueulbf4P4Q-9-a9YPbdyUZyF2A/edit#gid=847966271"

Meta <- read_sheet(gURL, sheet = "Sample_data_corr") %>% 
  select(Sample_names, Sites, Sampler, duration, Type)


Plates <- read_sheet(gURL, sheet = "Plates", range = "A48:M66", col_types = "c") %>% 
  dplyr::rename(row = 1) %>% 
  filter(row %in% LETTERS[1:8]) %>% 
  mutate(Plate = rep(c("Plate_1", "Plate_2"), each = 8)) %>% 
  pivot_longer(!one_of(c("row", "Plate")), names_to = "col", values_to = "Sample_names") %>% 
  select(Plate, row, col, Sample_names)

Plates <- 
Plates %>% 
  filter(!is.na(Sample_names)) %>% 
  left_join(Meta) %>% 
  mutate(Type = case_when(
    grepl("BLANK", Sample_names) ~ "extr_blank",
    grepl("_NC", Sample_names) ~ "field_control",
    grepl("PCR", Sample_names) ~ "PCR_control",
                          grepl("ymo", Sample_names) ~ "Zymo",
                          TRUE ~ Type))
```


```{r}
Plates %>% 
  mutate(row = factor(row, levels = LETTERS[8:1])) %>% 
  ggplot(aes(x =as.numeric(col), y = row))+
  geom_label(aes(label = Sample_names, colour = Type), size = 3)+
  facet_grid(Plate ~ .)
```

```{r}
shini_barcodes <- 
  read_xlsx(here("Documents", "Shini_barcodes_4_plates.xlsx")) %>% 
  mutate(Plate = rep(rep(paste("Plate", 1:4, sep = "_"), each = 96),2)) %>% 
  filter(Plate %in% c("Plate_1", "Plate_2")) %>% 
  dplyr::rename(Index = 1) %>% 
  select(Index, Plate) %>% 
  filter(grepl("_i5$", Index)) %>% 
  mutate(Index = gsub("(.+?)_i5", "\\1", Index)) %>% 
  group_by(Plate) %>% 
  mutate(row = rep(LETTERS[1:8], each = 12)) %>% 
  mutate(col = as.character(rep(1:12, 8)))

ASV_sp <- read_tsv(here("Data","iSeq", "Bac_ASW_glom.txt"))
Bac_tax_glom <- read_tsv(here("Data","iSeq", "Bac_taxa_glom.txt"))

DNAC <- read_tsv(here("Data", "DNA_conc_air_sampler_comp.txt"))

```

```{r}
Meta <- 
Plates %>% 
  left_join(shini_barcodes)
```

```{r}
flow_rate <- 
  Meta %>% 
  filter(Type == "active" & Sampler != "Drone") %>% 
  select(Sampler, duration) %>% 
  distinct() %>% 
  mutate(flow = case_when(
    Sampler == "Hepa" ~ 60,
    Sampler == "Kärcher" ~ 3000,
    Sampler == "Sass" ~ 300,
    Sampler == "Coriolis" ~ 300,
    Sampler == "Electrostatic" ~ 10,
    Sampler == "Burkhart" ~ 16.5,
  )) %>% 
  mutate(air_vol = case_when(
    duration == "30 min" ~ flow*30,
    duration == "5 hours" ~ flow*5*60
  ))
```


```{r}
ASV_tax_long <- 
ASV_sp %>% 
  pivot_longer(-Sample, names_to = "seq", values_to = "reads") %>% 
  dplyr::rename(Index = Sample) %>% 
  left_join(Meta) %>% 
  left_join(Bac_tax_glom)
```

# clean data

## PCR blanks
```{r}

ASV_tax_long %>% 
  filter(grepl("control", Type)) %>% 
 # filter(reads > 0) %>% 
  group_by(Type) %>% 
  summarise(reads = sum(reads))

ASV_tax_long$Type %>% unique()
```


```{r}

rar_curve <- 
ASV_sp %>% 
  select(-Sample) %>% 
  as.matrix %>% 
  `rownames<-`(ASV_sp$Sample) %>% 
  `[`(rowSums(.) > 0,) %>% 
  rarecurve(x = .,step = 100, tidy = TRUE)

rar_curve %>% left_join(Meta, by = c("Site" = "Index")) %>% 
  filter(grepl("active|passive", Type)) %>% 
  ggplot(aes(x = Sample, y = Species, group = Site, colour = duration)) +
  geom_line()+
  facet_wrap(~Sampler)

```




```{r}
rar <- 
ASV_sp %>% 
  select(-Sample) %>% 
  as.matrix %>% 
  `rownames<-`(ASV_sp$Sample) %>% 
  `[`(rowSums(.) > 0,) %>% 
  rarefy(x = .,sample = 2500) 


```

```{r}
S_df <- 
rar %>% 
  data.frame(S = .) %>% 
  tibble::rownames_to_column(var = "Index") %>% 
  left_join(Meta) %>% 
  mutate(Sampler = factor(Sampler, levels= unique(.$Sampler)[c(10,1,4,3,11,8,5,9)]))
  
  unique(S_df$Sampler)[c(10,1,4,3,11,8,5,9)]
  
```

```{r}
S_df %>% 
  filter(!Type %in% c("active", "passive"))
```


```{r}
S_df %>% 
  filter(Type %in% c("active", "passive")) %>% 
  filter(Sampler != "Drone") %>% 
  ggplot(aes(y = S, x = duration,  colour = Sites))+
  facet_grid(~Sampler, scales = "free_x")+
  geom_line(aes(group = Sites), size = 0.2, colour = "grey")+
  geom_point()+
  theme_minimal()+
  scale_color_brewer(palette = "Set1")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5),
        legend.position = "bottom")
```

```{r}
S_df %>% 
  left_join(flow_rate) %>% 
  filter(Type == "active" & Sampler != "Drone") %>% 
  ggplot(aes(x = air_vol, y = S, colour = Sampler))+
  geom_line(aes(group = Sites), size = 0.2, colour = "grey")+
  geom_point()+
  facet_grid(~duration)+
  scale_x_log10()+
  scale_color_brewer(palette = "Set1")+
  theme_bw()
  

```

# NMDS

```{r}
Sample_sub <- 
  Meta %>% 
  filter(Type %in% c("active", "passive")) %>% 
  pull(Index)

ASV_M <- 
ASV %>% 
  filter(Sample %in% Sample_sub) %>% 
  select(-Sample) %>% 
  as.matrix()

rownames(ASV_M) <- ASV %>% 
  filter(Sample %in% Sample_sub) %>% 
  pull(Sample)


NMDS <- metaMDS(ASV_M, autotransform = TRUE)

NMDS$points %>% 
  as.data.frame() %>% 
  tibble::rownames_to_column(var = "Index") %>% 
  left_join(Meta) %>% 
 # filter(duration == "5 hours") %>% 
  ggplot(aes(x = MDS1, y = MDS2, colour = Sampler, shape = duration))+
  geom_point()+
  facet_wrap(~Sites)+
  scale_color_brewer(palette = "Set1")+
  theme_bw()
```

```{r}
top_100 <- 
  ASV_tax_long %>% 
  group_by(seq) %>% 
  summarise(reads = median(reads)) %>% 
  arrange(desc(reads)) %>% 
  dplyr::slice(1:100) %>% 
  pull(seq)

ASV_tax_long %>%
  filter(seq %in% top_100) %>% 
  filter(Type %in% c("active")) %>% 
  filter(Sampler != "Drone") %>% 
  ggplot(aes(y = forcats::fct_rev(seq), x = Sampler, fill = log(reads, 10)))+
  geom_tile()+
  facet_grid(duration~Sites)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))+
  scale_fill_viridis_c(na.value = "white")
  
```

