---
title: "Vertebrate data analysis"
output: html_notebook
---

```{r}
library(dplyr)
library(tidyr)
library(here)
library(readr)
library(ggplot2)
library(googlesheets4)
library(vegan)
library(readxl)
```

#load metadata
```{r}
gURL <- "https://docs.google.com/spreadsheets/d/1GKWzD0q683oH3I_i5ueulbf4P4Q-9-a9YPbdyUZyF2A/edit#gid=847966271"

#load metadata
Meta <- read_sheet(gURL, sheet = "Sample_data_corr") %>% 
  select(Sample_names, Sites, Sampler, duration, Type)

# get plate layout
Plates <- read_sheet(gURL, sheet = "Plates", range = "A1:M21", col_types = "c") %>% 
  dplyr::rename(row = 1) %>% 
  filter(row %in% LETTERS[1:8]) %>% 
  mutate(Plate = rep(c("Plate_1", "Plate_2"), each = 8)) %>% 
  pivot_longer(!one_of(c("row", "Plate")), names_to = "col", values_to = "Sample_names") %>% 
  select(Plate, row, col, Sample_names) %>% 
  filter(!is.na(Sample_names)) %>% 
  left_join(Meta) %>% 
  mutate(Type = case_when(grepl("PCR", Sample_names) ~ "PCR_control",
                          TRUE ~ Type))

# get plate layout of barcodes 
shini_barcodes <- 
  read_xlsx(here("Documents", "Shini_barcodes_4_plates.xlsx")) %>% 
  mutate(Plate = rep(rep(paste("Plate", 1:4, sep = "_"), each = 96),2)) %>% 
  filter(Plate %in% c("Plate_1", "Plate_2")) %>% 
  dplyr::rename(Index = 1) %>% 
  select(Index, Plate) %>% 
  filter(grepl("_i5$", Index)) %>% 
  mutate(Index = gsub("(.+?)_i5", "\\1", Index)) %>% 
  group_by(Plate) %>% 
  mutate(row = rep(LETTERS[1:8], each = 12)) %>% 
  mutate(col = as.character(rep(1:12, 8)))

#match plate_layout and metadata
Meta <- 
Plates %>% 
  left_join(shini_barcodes)
```

#load data
```{r}
ASV_sp <- read_tsv(here("Data", "Vert_ASV_sp.text")) %>% 
  mutate(Sample = gsub(".+?(NGS.+)", "\\1", Sample))

Vert_tax_glom <- read_tsv(here("Data", "Vert_tax_sp.txt"))

DNAC <- read_tsv(here("Data", "DNA_conc_air_sampler_comp.txt"))
```


# clean data
```{r}
ASV_tax_long <- 
ASV_sp %>% 
  pivot_longer(-Sample, names_to = "seq", values_to = "reads") %>% 
  dplyr::rename(Index = Sample) %>% 
  left_join(Meta) %>% 
  left_join(Vert_tax_glom)
```

```{r}
unknown_Index <- ASV_sp$Sample[!ASV_sp$Sample %in% Meta$Index]

ASV_tax_long %>% 
  filter(Index %in% unknown_Index) %>% 
  filter(reads > 0)
```

## reads

```{r}
ASV_tax_long %>% 
  group_by(Sample_names) %>% 
  summarise(reads = sum(reads)) %>% 
  left_join(Meta) %>% 
  mutate(Sampler = ifelse(is.na(Sampler), Type, Sampler)) %>% 
  filter(!is.na(Type)) %>% 
  mutate(Sampler = fct_relevel(Sampler, c("PCR_control", "Extraction Blanks"), after = Inf)) %>% 
  ggplot(aes(x = Sampler, y= reads, colour = Type))+
  geom_point(position = position_dodge(width = 0.5))+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_brewer(palette = "Set1")
  
```

```{r}
ASV_tax_long %>% 
  group_by(Sample_names) %>% 
#  mutate(reads = ifelse(reads >= 50, reads, 0)) %>% 
  summarise(n_seq = sum(reads>0)) %>% 
  left_join(Meta) %>% 
  mutate(Sampler = ifelse(is.na(Sampler), Type, Sampler)) %>% 
  filter(!is.na(Type)) %>% 
  mutate(Sampler = fct_relevel(Sampler, c("PCR_control", "Extraction Blanks"), after = Inf)) %>% 
  ggplot(aes(x = Sampler, y= n_seq, colour = Type))+
  geom_point(position = position_dodge(width = 0.5))+
  #scale_y_log10()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_brewer(palette = "Set1")
```

```{r}

ASV_tax_long %>% 
  filter(grepl("control", Type)) %>% 
#  filter(grepl("Extr|PCR", Type)) %>% 
  group_by(Type, seq) %>% 
  summarise(reads = max(reads)) %>% 
  filter(reads > 0) %>% 
  arrange(desc(reads)) %>% 
  left_join(Vert_tax_glom)
  
```

```{r}
filter_df <- 
tibble(filter_thresh = c(0,2^(1:12)))

filter_df$n_seq <- 
lapply(filter_df$filter_thresh, function(x) {
  ASV_tax_long %>% 
    filter(reads > x) %>% 
    pull(seq) %>% unique %>% length()
}) %>% unlist() %>% as.numeric()

filter_df %>% 
ggplot(aes(x = filter_thresh,
           y = n_seq))+
  geom_point()+
  geom_text(aes(label = filter_thresh), hjust = -1)+
 # scale_y_log10()+
  labs(title = "Unique OTUs vs Sample_wide read threshold",
       x = "OTU read threshold (in each Sample)",
       y = "unique OTUs")
```

```{r}

Vert_ASV <- 
Vert_tax_glom %>% 
  filter(phylum %in% c("Chordata")) %>% 
  filter(species != "Homo sapiens") %>% 
  pull(seq)

ASV_sp <- ASV_sp[,colnames(ASV_sp) %in% c("Sample", Vert_ASV)]
ASV_tax_long <- ASV_tax_long %>% filter(seq %in% Vert_ASV) 
```

#prevalence
```{r}
apply(ASV_sp[,-1],2, function(x) sum(x >0) ) %>% 
  data.frame(prev = .) %>% 
  tibble::rownames_to_column(var = "seq") %>% 
  left_join(Vert_tax_glom) %>% 
  arrange(desc(prev)) %>% 
  mutate(rank = 1:n()) %>% 
  ggplot(aes(x = rank, y = prev))+
    geom_point()
```


## Species richness


```{r}

rar_curve <- 
ASV_sp %>% 
  #select({filter(Vert_tax_glom, phylum == "Basidiomycota") %>% pull(seq)}) %>% 
  select(-Sample) %>% 
  as.matrix %>% 
  `rownames<-`(ASV_sp$Sample) %>% 
  `[`(rowSums(.) > 0,) %>% 
  rarecurve(x = .,step = 1000, tidy = TRUE)

rar_curve %>% left_join(Meta, by = c("Site" = "Index")) %>% 
  filter(grepl("active|passive", Type)) %>% 
  ggplot(aes(x = Sample, y = Species, group = Site, colour = duration)) +
  geom_line()+
  facet_wrap(~Sampler)

```

given the few detected species rarefaction does not make sense for this dataset



```{r}

S_df <- 
ASV_tax_long %>% 
  group_by(Index, Sampler, Type, Sites, duration) %>% 
  summarise(S = sum(reads > 0)) %>% 
  filter(Type %in% c("active", "passive")) %>% 
  filter(Sampler != "Drone") %>% 
  mutate(Sampler = factor(Sampler, levels= unique(.$Sampler)[c(8,1,3,2,5,6,4,7)])) 

S_df %>% 
  ggplot(aes(y = S, x = duration,  colour = Sites))+
  facet_grid(~Sampler, scales = "free_x")+
  geom_line(aes(group = Sites), size = 0.2, colour = "grey", position = position_dodge(width = 0.6))+
  geom_point(position = position_dodge(width = 0.4))+
  theme_minimal()+
  scale_color_brewer(palette = "Set1")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5),
        legend.position = "bottom")
```

export richness
```{r}
S_df %>% 
  mutate(taxon = "Vertebrates") %>% 
  write_tsv(here("Data", "Vertebrate_richness.txt"))
```

### richness vs air volume

```{r}
flow_rate <- 
  Meta %>% 
  filter(Type == "active" & Sampler != "Drone") %>% 
  select(Sampler, duration) %>% 
  distinct() %>% 
  mutate(flow = case_when(
    Sampler == "Hepa" ~ 60,
    Sampler == "Kärcher" ~ 3000,
    Sampler == "Sass" ~ 300,
    Sampler == "Coriolis" ~ 300,
    Sampler == "Electrostatic" ~ 10,
    Sampler == "Burkhart" ~ 16.5,
  )) %>% 
  mutate(air_vol = case_when(
    duration == "30 min" ~ flow*30,
    duration == "5 hours" ~ flow*5*60
  ))
```


```{r}
S_df %>% 
  left_join(flow_rate) %>% 
  filter(Type == "active" & Sampler != "Drone") %>% 
  ggplot(aes(x = air_vol, y = S, colour = Sampler, shape = duration))+
  #geom_line(aes(group = Sites), size = 0.2, colour = "grey")+
  geom_point(position = position_dodge(width = 0.4))+
 # facet_grid(~duration)+
  geom_smooth(aes(group = 1), method = "lm", colour = "darkblue", size = 0.2)+
#  geom_smooth(aes(group = duration), method = "lm", colour = "darkred", size = 0.2, se = F)+
  scale_x_log10()+
  scale_color_brewer(palette = "Set1")+
  theme_bw()
  

```

```{r}
ASV_tax_long %>% 
  filter(Type %in% c("active", "passive")) %>% 
  filter(Sampler != "Drone") %>%
  arrange(class, order, family, genus, species) %>% 
  mutate(species = factor(species, levels = unique(species))) %>% 
  filter(reads > 0) %>% 
  group_by(duration, Sampler, species) %>%
  summarise(Sites = as.character(sum(reads > 0))) %>% 
  left_join(distinct(select(Vert_tax_glom, class, order, family, genus, species))) %>% 
  ggplot(aes(x = Sampler, y = species, size = Sites, colour = duration))+
  geom_point(shape = 21)+
  facet_nested(class + order~duration, scales = "free", space = "free", nest_line = TRUE)+
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  scale_colour_brewer(palette = "Set1")+
  theme(
    strip.text.y.right = element_text(angle = 0, size = 8),
    plot.margin = margin(0.5, 0.5, 0.5, 0.5, unit = "cm"),
   # plot.title = element_text(size = 15, face = "bold"),
    strip.placement = "outside",
    axis.title.y = element_blank(),
    axis.text = element_text(size = 8),
    legend.position = "bottom",
   strip.background = element_blank(),
        ggh4x.facet.nestline = element_line(colour = "darkblue")
   # panel.grid.major.y = element_blank(),
    )
```


```{r}
ASV_tax_long %>% 
  filter(Type %in% c("active", "passive")) %>% 
  filter(reads > 0) %>% 
  filter(!is.na(genus)) %>% 
  group_by(Sites, Sampler, duration,genus) %>% 
  summarise(n = n()) %>% 
 # left_join(distinct(select(ASV_tax_long, Sampler, Sites, duration, genus)), . ) %>% 
  filter(!is.na(duration) & !is.na(genus)) %>% 
  filter(Sampler != "Drone") %>% 
  left_join(distinct(select(COI_taxa_80_glom, class, order, family, genus))) %>% 
  arrange(class, order, family, genus) %>% 
  mutate(genus = factor(genus, levels = unique(.$genus))) %>% 
  ggplot(aes(y = genus, x = Sampler, size = n, colour = duration))+
  geom_point(shape = 21)+
  facet_nested(class + order~Sites, scales = "free", space = "free", nest_line = TRUE)+
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))+
  scale_colour_brewer(palette = "Set1")+
  theme(
    strip.text.y.right = element_text(angle = 0, size = 8),
    plot.margin = margin(0.5, 0.5, 0.5, 0.5, unit = "cm"),
   # plot.title = element_text(size = 15, face = "bold"),
    strip.placement = "outside",
    axis.title.y = element_blank(),
    axis.text = element_text(size = 8),
    legend.position = "bottom",
   strip.background = element_blank(),
        ggh4x.facet.nestline = element_line(colour = "darkblue")
   # panel.grid.major.y = element_blank(),
    )
  
  
```


