---
title: "Insect data analysis"
output: html_notebook
---

```{r}
library(dplyr)
library(tidyr)
library(here)
library(readr)
library(ggplot2)
library(ggh4x)
library(googlesheets4)
library(vegan)
library(readxl)
```

#load metadata
```{r}
meta <- read_tsv(here("Data", "Meta_data.tsv"))

gURL <- "https://docs.google.com/spreadsheets/d/1GKWzD0q683oH3I_i5ueulbf4P4Q-9-a9YPbdyUZyF2A/edit#gid=847966271"

#load metadata
Meta <- read_sheet(gURL, sheet = "Sample_data_corr") %>% 
  select(Sample_names, Sites, Sampler, duration, Type)

# get plate layout
Plates <- read_sheet(gURL, sheet = "Plates", range = "A1:M21", col_types = "c") %>% 
  dplyr::rename(row = 1) %>% 
  filter(row %in% LETTERS[1:8]) %>% 
  mutate(Plate = rep(c("Plate_1", "Plate_2"), each = 8)) %>% 
  pivot_longer(!one_of(c("row", "Plate")), names_to = "col", values_to = "Sample_names") %>% 
  select(Plate, row, col, Sample_names) %>% 
  filter(!is.na(Sample_names)) %>% 
  left_join(Meta) %>% 
  mutate(Type = case_when(grepl("PCR", Sample_names) ~ "PCR_control",
                          TRUE ~ Type))

# get plate layout of barcodes 
shini_barcodes <- 
  read_xlsx(here("Documents", "Shini_barcodes_4_plates.xlsx")) %>% 
  mutate(Plate = rep(rep(paste("Plate", 1:4, sep = "_"), each = 96),2)) %>% 
  filter(Plate %in% c("Plate_1", "Plate_2")) %>% 
  dplyr::rename(Index = 1) %>% 
  select(Index, Plate) %>% 
  filter(grepl("_i5$", Index)) %>% 
  mutate(Index = gsub("(.+?)_i5", "\\1", Index)) %>% 
  group_by(Plate) %>% 
  mutate(row = rep(LETTERS[1:8], each = 12)) %>% 
  mutate(col = as.character(rep(1:12, 8)))

#match plate_layout and metadata
Meta <- 
Plates %>% 
  left_join(shini_barcodes)
```

#load data
```{r}
ASV_sp <- read_tsv(here("Data", "Insects", "out_final", "Insects_ASV_glom.txt"))
  

COI_taxa_80_glom <- read_tsv(here("Data", "Insects", "out_final", "Insects_taxa_80_glom.txt"))

DNAC <- read_tsv(here("Data", "DNA_conc_air_sampler_comp.txt"))

syrphid_seq <- 
COI_taxa_80_glom %>% 
  filter(family == "Syrphidae") %>% pull(seq)

ASV_sp %>% select(1, one_of(syrphid_seq)) %>% 
  pivot_longer(-Sample) %>% 
  filter(value > 0) %>% 
  mutate(Index = gsub(".+(NGS_.+)", "\\1", Sample)) %>% 
  left_join(meta)

  meta

```


# clean data
```{r}
ASV_tax_long <- 
ASV_sp %>% 
  pivot_longer(-Sample, names_to = "seq", values_to = "reads") %>% 
  dplyr::rename(Index = Sample) %>% 
  left_join(Meta) %>% 
  left_join(COI_taxa_80_glom)
```

```{r}

unknown_Index <- ASV_sp$Sample[!ASV_sp$Sample %in% Meta$Index]

ASV_tax_long %>% 
  filter(Index %in% unknown_Index) %>% 
  filter(reads > 0)

```

## reads

```{r}
ASV_tax_long %>% 
  group_by(Sample_names) %>% 
  summarise(reads = sum(reads)) %>% 
  left_join(Meta) %>% 
  mutate(Sampler = ifelse(is.na(Sampler), Type, Sampler)) %>% 
  filter(!is.na(Type)) %>% 
  mutate(Sampler = fct_relevel(Sampler, c("PCR_control", "Extraction Blanks"), after = Inf)) %>% 
  ggplot(aes(x = Sampler, y= reads, colour = Type))+
  geom_point(position = position_dodge(width = 0.5))+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_brewer(palette = "Set1")
  
```

```{r}
ASV_tax_long %>% 
  group_by(Sample_names) %>% 
  mutate(reads = ifelse(reads >= 50, reads, 0)) %>% 
  summarise(n_seq = sum(reads>0)) %>% 
  left_join(Meta) %>% 
  mutate(Sampler = ifelse(is.na(Sampler), Type, Sampler)) %>% 
  filter(!is.na(Type)) %>% 
  mutate(Sampler = fct_relevel(Sampler, c("PCR_control", "Extraction Blanks"), after = Inf)) %>% 
  ggplot(aes(x = Sampler, y= n_seq, colour = Type))+
  geom_point(position = position_dodge(width = 0.5))+
  #scale_y_log10()+
  theme(axis.text.x = element_text(angle = 90))+
  scale_color_brewer(palette = "Set1")
```

```{r}
ASV_tax_long %>% 
  filter(grepl("BLANK", Sample_names)) %>% 
  group_by(Sample_names) %>% 
  summarise(n_seq = sum(reads > 0), reads = sum(reads))

#Blank8 has the most sequences, maybe a drop? 

ASV_tax_long %>% 
 # filter(Sample_names != "BLANK_8") %>% 
  filter(grepl("control", Type)) %>% 
#  filter(grepl("Extr|PCR", Type)) %>% 
  group_by(Type, seq) %>% 
  summarise(reads = max(reads)) %>% 
  filter(reads > 0) %>% 
  arrange(desc(reads)) %>% 
  left_join(COI_taxa_80_glom)
  
```

```{r}
filter_df <- 
tibble(filter_thresh = c(0,2^(1:12)))

filter_df$n_seq <- 
lapply(filter_df$filter_thresh, function(x) {
  ASV_tax_long %>% 
    filter(reads > x) %>% 
    pull(seq) %>% unique %>% length()
}) %>% unlist() %>% as.numeric()

filter_df %>% 
ggplot(aes(x = filter_thresh,
           y = n_seq))+
  geom_point()+
  geom_text(aes(label = filter_thresh), hjust = -1)+
 # scale_y_log10()+
  labs(title = "Unique OTUs vs Sample_wide read threshold",
       x = "OTU read threshold (in each Sample)",
       y = "unique OTUs")
```

```{r}

COI_ASV <- 
COI_taxa_80_glom %>% 
  filter(phylum %in% c("Arthropoda")) %>% 
  pull(seq)

ASV_sp <- ASV_sp[,colnames(ASV_sp) %in% c("Sample", COI_ASV)]
  
```

#prevalence
```{r}
apply(ASV_sp[,-1],2, function(x) sum(x >0) ) %>% 
  data.frame(prev = .) %>% 
  tibble::rownames_to_column(var = "seq") %>% 
  left_join(COI_taxa_80_glom) %>% 
  arrange(desc(prev)) %>% 
  mutate(rank = 1:n()) %>% 
  ggplot(aes(x = rank, y = prev))+
    geom_point()
```


```{r}
ASV_tax_long <- 
ASV_sp %>% 
  pivot_longer(-Sample, names_to = "seq", values_to = "reads") %>% 
  dplyr::rename(Index = Sample) %>% 
  left_join(Meta) %>% 
  left_join(COI_taxa_80_glom)
```

```{r}
#per sample read threshold

thresh <- 1

ASV_sp_t <- 
  ASV_sp %>% 
  mutate(across(where(is.numeric), function(x){ifelse(x >= thresh, x, 0)}))
  
```


## Species richness


```{r}

rar_curve <- 
ASV_sp_t %>% 
  #select({filter(COI_taxa_80_glom, phylum == "Basidiomycota") %>% pull(seq)}) %>% 
  select(-Sample) %>% 
  as.matrix %>% 
  `rownames<-`(ASV_sp$Sample) %>% 
  `[`(rowSums(.) > 0,) %>% 
  rarecurve(x = .,step = 1000, tidy = TRUE)

rar_curve %>% left_join(Meta, by = c("Site" = "Index")) %>% 
  filter(grepl("active|passive", Type)) %>% 
  ggplot(aes(x = Sample, y = Species, group = Site, colour = duration)) +
  geom_line()+
  facet_wrap(~Sampler)

```




```{r}

rar <- 
ASV_sp_t %>% 
  select(-Sample) %>% 
  as.matrix %>% 
  `rownames<-`(ASV_sp$Sample) %>% 
  `[`(rowSums(.) > 0,) %>% 
  rarefy(x = .,sample = 0.5e5) 

```
```{r}

S_df <- 
rar %>% 
  data.frame(S = .) %>% 
  dplyr::add_rownames(var = "Index") %>% 
  left_join(Meta) %>% 
  filter(Type %in% c("active", "passive")) %>% 
  filter(Sampler != "Drone") %>% 
  mutate(Sampler = factor(Sampler, levels= unique(.$Sampler)[c(8,1,3,2,5,6,4,7)])) 

S_df %>% 
  ggplot(aes(y = S, x = duration,  colour = Sites))+
  facet_grid(~Sampler, scales = "free_x")+
  geom_line(aes(group = Sites), size = 0.2, colour = "grey")+
  geom_point()+
  theme_minimal()+
  scale_color_brewer(palette = "Set1")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5),
        legend.position = "bottom")
```

export richness
```{r}
S_df %>% 
  mutate(taxon = "Insects") %>% 
  write_tsv(here("Data", "Insect_richness.txt"))
```

### richness vs air volume

```{r}
flow_rate <- 
  Meta %>% 
  filter(Type == "active" & Sampler != "Drone") %>% 
  select(Sampler, duration) %>% 
  distinct() %>% 
  mutate(flow = case_when(
    Sampler == "Hepa" ~ 60,
    Sampler == "Kärcher" ~ 3000,
    Sampler == "Sass" ~ 300,
    Sampler == "Coriolis" ~ 300,
    Sampler == "Electrostatic" ~ 10,
    Sampler == "Burkhart" ~ 16.5,
  )) %>% 
  mutate(air_vol = case_when(
    duration == "30 min" ~ flow*30,
    duration == "5 hours" ~ flow*5*60
  ))
```


```{r}
S_df %>% 
  left_join(flow_rate) %>% 
  filter(Type == "active" & Sampler != "Drone") %>% 
  ggplot(aes(x = air_vol, y = S, colour = Sampler, shape = duration))+
  #geom_line(aes(group = Sites), size = 0.2, colour = "grey")+
  geom_point(position = position_jitter(width = 0.05))+
 # facet_grid(~duration)+
  geom_smooth(aes(group = 1), method = "lm", colour = "darkblue", size = 0.2)+
#  geom_smooth(aes(group = duration), method = "lm", colour = "darkred", size = 0.2, se = F)+
  scale_x_log10()+
  scale_color_brewer(palette = "Set1")+
  theme_bw()
  

```

### richness corr

```{r}
Cor_mat <- 
S_df %>% 
  left_join(flow_rate) %>% 
  filter(Type %in% c("active", "passive")) %>% 
  mutate(Sampler = paste(Sampler, duration)) %>% 
  arrange(Type, duration, desc(flow)) %>% 
  #filter(duration == "5 hours") %>% 
  select(Sites, Sampler, S) %>% 
  pivot_wider(names_from = Sampler, values_from = S) %>% 
  mutate(across(where(~sum(is.na(.)) > 2), function(x) return(NA))) %>% 
  select(-Sites) %>% 
  cor(method = "pearson", use = "pairwise.complete.obs") 



{  
Cor_mat %>% 
  corrplot(type = "lower",diag = F,tl.col = "black", tl.cex = 0.8, method = "ellipse",
           na.label = "square", na.label.col = "lightgrey")
  
rect(xleft = 0.5, ybottom = 8.5, xright = 5.5, ytop = 13.5, density = NULL, angle = 45,
     col = NULL, border = "darkred", lty = par("lty"), lwd = par("lwd"))

rect(xleft = 6.5, ybottom = 2.5, xright = 11.5, ytop = 7.5, density = NULL, angle = 45,
     col = NULL, border = "darkred", lty = par("lty"), lwd = par("lwd"))

}
         
```
### sample completeness
```{r}
ASV_sample_based <- 
  ASV_tax_long %>% 
  group_by(Index, duration, Sites, Sampler, seq) %>% 
  filter(Type %in% c("active", "passive")) %>% 
  filter(Sampler != "Drone") %>% 
  summarise(reads = sum(reads)) %>% 
  mutate(reads = as.numeric(reads > 0)) %>% 
  pivot_wider(names_from = seq, values_from = reads)
  
site_rar_df <- 
ASV_sample_based %>% 
  split(~Sampler+duration) 

site_rar_df <- 
site_rar_df[unlist(lapply(site_rar_df, nrow))>0] %>% 
  lapply(., function(x){
    
  if(nrow(x) > 0){res <- vegan::specaccum(x[,-c(1:4)])}
    
    resdf = tibble(sites = res$sites,
                   Richness = res$richness,
                   sd = res$sd)
    
    return(resdf)
  })

site_rar_df %>% 
  bind_rows(.id = "var") %>% 
  tidyr::separate_wider_delim(col = var, names = c("Sampler", "duration"), delim = ".") %>% 
  ggplot(aes(x = sites, y = Richness, fill = duration))+
  geom_line()+
  geom_ribbon(aes(ymin = Richness - sd, ymax = Richness + sd), colouor = NULL, alpha = 0.5)+
  facet_wrap(.~Sampler)+
  scale_x_continuous(breaks = seq(1,8,1))
```

## Species comp

```{r}
ASV_sample <- 
ASV_sp %>% 
  filter(Sample != Meta[Meta$Sample_names == "1DB30_1",]$Index) %>% 
  filter(Sample %in% {filter(Meta, Type %in% c("active", "passive")) %>% pull(Index)}) %>% 
  filter(rowSums(.[,-1])>0) %>% 
  select(where(function(x){is.character(x) || sum(x) > 1}))

ASV_dist <- vegdist(ASV_sample[,-1], method = "bray", binary = T)

NMDS <- metaMDS(ASV_dist) 

NMDS$points %>% 
  as_tibble() %>% 
  mutate(Index = ASV_sample$Sample) %>% 
  left_join(Meta) %>% 
  ggplot(aes(x = MDS1, y = MDS2, colour = Sampler))+
  geom_point()+
  facet_wrap(~duration)
  
```

```{r}
adonis2(ASV_dist~ Sampler + Sites + duration, data = Meta[Meta$Index %in% ASV_sample$Sample,])
```

### similarity ranking

```{r}
ASV_dist_M <- as.matrix(ASV_dist)

dimnames(ASV_dist_M) <- 
  list(ASV_sample$Sample, ASV_sample$Sample) 

diag(ASV_dist_M) <- NA

Meta_comb1 <- 
  Meta %>% 
  mutate(comb1 = paste(Sampler, duration, Sites)) %>% 
  select(Index, comb1)

Meta_comb2 <- 
  Meta %>% 
  mutate(comb2 = paste(Sampler, duration, Sites)) %>% 
  select(Index, comb2) %>% 
  dplyr::rename(Index2 = Index)

ASV_dist_df <-   
ASV_dist_M %>% 
  data.frame() %>% 
  tibble::rownames_to_column(var = "Index") %>% 
  pivot_longer(-Index, names_to = "Index2") %>% 
  filter(!is.na(value)) %>% 
  left_join(Meta_comb1) %>% 
  left_join(Meta_comb2) 

ASV_dist_cor <- 
ASV_dist_df %>% 
  filter(!grepl("Drone", comb1) & !grepl("Drone", comb2)) %>%
  mutate(site_comb = paste(gsub(".+\\s(\\w+)$", "\\1", comb1),
                           gsub(".+\\s(\\w+)$", "\\1", comb2),
                           sep = "_")) %>% 
  mutate(Sampler1 = gsub("(.+)\\s\\w+$", "\\1", comb1),
         Sampler2 = gsub("(.+)\\s\\w+$", "\\1", comb2)) %>% 
  filter(Sampler1 == Sampler2) %>% 
  select(value, site_comb, Sampler1) %>% 
#  group_by(site_comb, Sampler1) %>% 
#  filter(n() > 1)
  pivot_wider(names_from = Sampler1, values_from = value) %>% 
  select(-site_comb) %>% 
  distinct() %>% 
  select(rownames(Cor_mat)) %>% 
  cor(method = "pearson") %>% 
  #cor(method = "kendall") %>% 
  {.}
                              
ASV_dist_cor %>% 
  corrplot(type = "lower",diag = F,tl.col = "black", tl.cex = 0.8, method = "ellipse",
           na.label = "square", na.label.col = "white")

```

```{r}

p1 <- 
ASV_tax_long %>% 
  filter(Type %in% c("active", "passive")) %>% 
  filter(reads > 0) %>% 
  filter(!is.na(genus)) %>% 
  group_by(Sites, Sampler, duration,genus) %>% 
  summarise(n = n()) %>% 
 # left_join(distinct(select(ASV_tax_long, Sampler, Sites, duration, genus)), . ) %>% 
  filter(!is.na(duration) & !is.na(genus)) %>% 
  filter(Sampler != "Drone") %>% 
  left_join(distinct(select(COI_taxa_80_glom, class, order, family, genus))) %>% 
  arrange(class, order, family, genus) %>% 
  mutate(genus = factor(genus, levels = unique(.$genus))) %>% 
  ggplot(aes(y = genus, x = Sampler, size = n, colour = duration))+
  geom_point(shape = 21)+
  facet_nested(class + order~Sites, scales = "free", space = "free", nest_line = TRUE)+
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))+
  scale_colour_brewer(palette = "Set1")+
  theme(
    strip.text.y.right = element_text(angle = 0, size = 8),
    plot.margin = margin(0.5, 0.5, 0.5, 0.5, unit = "cm"),
   # plot.title = element_text(size = 15, face = "bold"),
    strip.placement = "outside",
    axis.title.y = element_blank(),
    axis.text = element_text(size = 8),
    legend.position = "bottom",
   strip.background = element_blank(),
        ggh4x.facet.nestline = element_line(colour = "darkblue")
   # panel.grid.major.y = element_blank(),
    )

ggsave(here("Figures", "Insect_genus_bubble.jpg"), width = 10, height = 14)
  
```

## Venn diagramm
```{r}
sampler_venn <- 
ASV_tax_long %>% 
  filter(Sampler != "Drone") %>% 
  filter(duration %in% c("30 min", "5 hours")) %>% 
 # filter(Sampler %in% c("Kärcher", "Sass", "Coriolis", "Hepa")) %>% 
  group_by(Sampler, duration, seq) %>% 
  summarise(reads = sum(reads)) %>% 
  mutate(reads = reads > 0) %>% 
  pivot_wider(names_from = duration, values_from = reads) %>% 
  select(-seq) %>% 
  euler(shape = "ellipse", by = list(Sampler)) 

#sampler_venn
eulerr_options(quantities = list(fontsize= 6, col = "darkred", cex = 1.2, fontfamily = "sans"))

plot(sampler_venn, legend = TRUE, quantities = TRUE)
```


```{r}
active <- 
ASV_tax_long %>% 
  filter(Sampler != "Drone") %>% 
  filter(duration %in% c("5 hours")) %>% 
  filter(Sampler %in% c("Kärcher", "Sass", "Coriolis", "Hepa")) %>% 
  group_by(Type, Sampler, seq) %>% 
  summarise(reads = sum(reads)) %>% 
  mutate(reads = reads > 0) 

passive <- 
  ASV_tax_long %>% 
  filter(Sampler != "Drone") %>% 
  filter(duration %in% c("2 weeks")) %>% 
  group_by(Type, Sampler, seq) %>% 
  summarise(reads = sum(reads)) %>% 
  mutate(reads = reads > 0) 

comp_df <- active %>% mutate(comp = "") %>% dplyr::slice(0)

for(i in unique(active$Sampler)){
  
  comp_df <- 
  active %>% 
    filter(Sampler == i) %>% 
    bind_rows(passive) %>% 
    mutate(comp = i) %>% 
    bind_rows(comp_df, .)

  
}

sampler_venn <- 
comp_df %>% 
  group_by(comp) %>% 
  mutate(Sampler = case_when(Type == "active" ~ "active",
                             TRUE ~ Sampler)) %>% 
  select(-Type) %>% 
  pivot_wider(names_from = Sampler, values_from = reads) %>% 
  select(-seq) %>% 
  euler(shape = "ellipse", by = list(comp)) 

sampler_venn

eulerr_options(quantities = list(fontsize= 8))

plot(sampler_venn, legend = TRUE, quantities = TRUE)
```

```{r}
sampler_venn <- 
ASV_tax_long %>% 
  filter(Sampler != "Drone") %>% 
  filter(duration == "5 hours") %>% 
  filter(Sampler %in% c("Kärcher", "Sass", "Coriolis", "Hepa")) %>% 
  group_by(Sampler, seq) %>% 
  summarise(reads = sum(reads)) %>% 
  mutate(reads = reads > 0) %>% 
  pivot_wider(names_from = Sampler, values_from = reads) %>% 
  select(-seq) %>% 
  euler(shape = "ellipse") 

eulerr_options(quantities = list(fontsize= 10, col = "black"))

plot(sampler_venn, legend = TRUE, quantities = TRUE)

ASV_tax_long %>% 
  filter(seq == "seq_5706") %>% #Odonata (dragon flies)
  filter(reads > 0)
```
#Primer

```{r}
ASV_sp <- read_tsv(here("Data", "COI_ASW_glom.txt")) %>% 
  mutate(Sample = gsub(".+?(NGS.+)", "\\1", Sample))

ASV_sp_long <- 
  ASV_sp %>% 
  pivot_longer(-Sample, names_to = "seq", values_to = "reads") %>% 
  group_by(seq) %>% 
  summarise(reads = sum(reads)) %>% 
  left_join(COI_taxa_80_glom) 

ASV_sp_long %>%   
group_by(kingdom) %>% 
  summarise(reads = sum(reads)) %>% 
  ungroup() %>% 
  mutate(read_prct = round(reads / sum(reads) * 100,2)) %>% 
  arrange(desc(read_prct))

ASV_sp_long %>%   
group_by(kingdom) %>% 
  summarise(nseq = n()) %>% 
  ungroup() %>% 
  mutate(nseq_prct = round(nseq / sum(nseq) * 100,2)) %>% 
  arrange(desc(nseq_prct))

```
```{r}
seqs <- readDNAStringSet(here("Data","AVITI", "Insects","ASV_swarm.fasta"))

NA_seq <- 
ASV_sp_long %>% 
  filter(is.na(kingdom)) %>% 
  arrange(desc(reads)) %>% 
  dplyr::slice(1:10) %>% 
  pull(seq)

seqs[NA_seq] %>% 
  as.character() %>% 
  paste(">",names(.),"\n",., sep = "") %>% 
  clipr::write_clip()
```


```{r}

system(
  paste(
    "/Applications/vsearch/bin/vsearch --uchime_denovo", 
    gsub("My Drive", "My\\\\ Drive", here("Data","AVITI", "Insects","ASV_swarm.fasta")),
    " --nonchimeras ",
    "~/Downloads/testchimera.fasta"
  )
)

```

