---
title: "R Notebook"
output: html_notebook
---

```{r}
richness_df <- 
list.files(here("Data"), pattern = ".+richness.txt", full.names = TRUE) %>% 
  lapply(read_tsv) %>% 
  bind_rows()
```

```{r}
richness_df %>% 
  mutate(Sampler = factor(Sampler, levels =  c("Kärcher","Coriolis", "Sass", "Hepa", 
                                               "Burkhart", "Electrostatic", "MWAC", 
                                               "WSL_Filter"))) %>% 
  mutate(taxon = factor(taxon, levels = c("Bacteria", "Fungi", "Plants", "Insects", "Vertebrates"))) %>% 
  ggplot(aes(y = S, x = duration,  colour = Sites))+
  facet_grid(taxon~Sampler, scales = "free")+
  geom_line(aes(group = Sites), size = 0.2, colour = "grey")+
  geom_point()+
  theme_minimal()+
  scale_color_brewer(palette = "Set1")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5),
        legend.position = "bottom",
        strip.text.y = element_text(angle=0))
```

```{r}
flow_rate <- 
  Meta %>% 
  filter(Type == "active" & Sampler != "Drone") %>% 
  select(Sampler, duration) %>% 
  distinct() %>% 
  mutate(flow = case_when(
    Sampler == "Hepa" ~ 60,
    Sampler == "Kärcher" ~ 3000,
    Sampler == "Sass" ~ 300,
    Sampler == "Coriolis" ~ 300,
    Sampler == "Electrostatic" ~ 10,
    Sampler == "Burkhart" ~ 16.5,
  )) %>% 
  mutate(air_vol = case_when(
    duration == "30 min" ~ flow*30,
    duration == "5 hours" ~ flow*5*60
  ))
```


```{r}
richness_df %>% 
  left_join(flow_rate) %>% 
  filter(Type == "active" & Sampler != "Drone") %>% 
  mutate(taxon = factor(taxon, levels = c("Bacteria", "Fungi", "Plants", "Insects", "Vertebrates"))) %>% 
  ggplot(aes(x = air_vol, y = S, colour = Sampler, shape = duration))+
  #geom_line(aes(group = Sites), size = 0.2, colour = "grey")+
  geom_point()+
  geom_smooth(aes(group = 1), method = "lm", colour = "darkblue", size = 0.2)+
  facet_grid(taxon~., scales = "free")+
  #facet_wrap(~taxon, scales="free_y", nrow = 1)+
#  geom_smooth(aes(group = duration), method = "lm", colour = "darkred", size = 0.2, se = F)+
  scale_x_log10()+
  scale_color_brewer(palette = "Set1")+
  theme_bw()+
  theme(legend.position = "left")+
  labs(x = "", y = "")
  NULL
  
  

```

