---
title: "Prep_Metadata"
author: "Fabian Roger"
date: "2025-07-29"
output: html_document
---

```{r}
library(dplyr)
library(readxl)
```


#load metadata
```{r}
#load metadata
Meta <- read_xlsx(here("Data", "sampler_comp_meta.xlsx"), sheet = "Sample_data_corr") %>% 
  select(Sample_names, Sites, Sampler, duration, Type)

# get plate layout
Plates <- read_xlsx(here("Data", "sampler_comp_meta.xlsx"), 
                    sheet = "Plates", range = "A26:M44") %>% 
  dplyr::rename(row = 1) %>% 
  filter(row %in% LETTERS[1:8]) %>% 
  mutate(Plate = rep(c("Plate_1", "Plate_2"), each = 8)) %>% 
  pivot_longer(!one_of(c("row", "Plate")), names_to = "col", values_to = "Sample_names") %>% 
  select(Plate, row, col, Sample_names) %>% 
  filter(!is.na(Sample_names)) %>% 
  left_join(Meta) %>% 
  mutate(Type = case_when(grepl("PCR", Sample_names) ~ "PCR_control",
                          TRUE ~ Type)) %>% 
  mutate(col = as.character(as.integer(col)))

# get plate layout of barcodes 
Barcodes <- 
  read_xlsx(here("Data", "Barcodes_4_plates.xlsx")) %>% 
  mutate(Plate = rep(rep(paste("Plate", 1:4, sep = "_"), each = 96),2)) %>% 
  filter(Plate %in% c("Plate_1", "Plate_2")) %>% 
  dplyr::rename(Index = 1) %>% 
  select(Index, Plate) %>% 
  filter(grepl("_i5$", Index)) %>% 
  mutate(Index = gsub("(.+?)_i5", "\\1", Index)) %>% 
  group_by(Plate) %>% 
  mutate(row = rep(LETTERS[1:8], each = 12)) %>% 
  mutate(col = as.character(rep(1:12, 8))) 

#match plate_layout and metadata
Meta <- 
Plates %>% 
  left_join(Barcodes)

#export
Meta %>% write_tsv(here("Data", "Meta_data.tsv"))
```